In [4]:
data = {
   "height":[1.4,1.2,1.0,1.5,1.8],
    "fav-movie":["baby-day-out", "the original", "pirates of the carribean", "tom and jerry", "wedneasday"]
}

In [6]:
type(data)

dict

In [9]:
import pandas as pd
df = pd.DataFrame(data)

In [11]:
df

   height                 fav-movie
0     1.4              baby-day-out
1     1.2              the original
2     1.0  pirates of the carribean
3     1.5             tom and jerry
4     1.8                wedneasday

###LABEL ENCODING

In [16]:
from sklearn.preprocessing import LabelEncoder

# 2. Initialize the LabelEncoder use only with ordered data of heirarchical data
le = LabelEncoder()

# 3. Fit to the column and transform text to integers
df['Encoded_class']=le.fit_transform(df['fav-movie'])
print(df)

   height                 fav-movie  Encoded_class
0     1.4              baby-day-out              0
1     1.2              the original              2
2     1.0  pirates of the carribean              1
3     1.5             tom and jerry              3
4     1.8                wedneasday              4

### ONE HOT ENCODING

In [22]:

df_encoded = pd.get_dummies(df, columns=['fav-movie'],dtype="int", drop_first=True)
# Print the resulting dataframe
# print(df_encoded)
df_encoded

,height,Encoded_class,fav-movie_pirates of the carribean,fav-movie_the original,fav-movie_tom and jerry,fav-movie_wedneasday
0,1.4,0,0,0,0,0
1,1.2,2,0,1,0,0
2,1.0,1,1,0,0,0
3,1.5,3,0,0,1,0
4,1.8,4,0,0,0,1

### BAG OF WORDS

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

# 1. Create a sample dataset with text reviews
datas = {"reviews": ["the food is good", "New food is terrible", "good food and good services"]}

df = pd.DataFrame(datas)

# 2. Initialize the CountVectorizer
# stop_words='english' removes useless words like 'the' and 'and' to save memory
vectorizer = CountVectorizer(stop_words='english')

# 3. Fit and transform the text column 
# This learns the unique vocabulary and counts the word occurrences 
bow_matrix = vectorizer.fit_transform(df['reviews'])

# 4. Convert the matrix into a clean Pandas DataFrame
# vectorizer.get_feature_names_out() extracts the learned vocabulary as column names 

df_bow = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out()) 
df_bow

   food  good  new  services  terrible
0     1     1    0         0         0
1     1     0    1         0         1
2     1     2    0         1         0

 ### TF-IDF 
 assignment

### WORD EMBEDDINGS

<h1>TOKENIZERS <h/>

Whitespace tokenizer

In [131]:
text = "Deep learning is amazing !"
tokens = text.split()
print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

In [132]:
text = "Deep learning is amazing !"
tokens = text.split("e")
print(tokens)

['D', '', 'p l', 'arning is amazing !']

###  word level tokenization that handles punctuation

In [133]:
import re
text = "Deep learning is amazing!"
tokens = re.findall(r"\w+|[^\w\s]", text)
print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

### CHARACTER LEVEL TOKENIZATION

In [134]:
texts = "amazing"
tokens =list(texts)
print(tokens)

['a', 'm', 'a', 'z', 'i', 'n', 'g']

###this is a step by step implementation of a simple tokenizer

In [135]:
with open ("text.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
len(raw_text),raw_text

(129,
 "me'ssi is the fi..rst go'at\nro'naldo is t.,he second goa't\nma'n-.city wil.l win the champoi;n's leauge\ni wi'll buy a pr/ivate jet")

### text cleaning using regular expressions

In [142]:
white_space_splitting = re.split(r'\s', raw_text)
print(white_space_splitting)

['messi', 'is', 'the', 'first', 'goat', 'ronaldo', 'is', 'the', 'second', 'goat', 'mancity', 'will', 'win', 'the', 'champoins', 'leauge', 'i', 'will', 'buy', 'a', 'private', 'jet']

In [143]:
len(white_space_splitting)

22

In [148]:
raw_text = re.sub(r'@\w+',"", raw_text, flags=re.MULTILINE)
raw_text = re.sub(r'#\w+',"", raw_text, flags=re.MULTILINE)
raw_text = re.sub(r'[^a-zA-Z\s]',"", raw_text)
raw_text = re.sub(r'\s+',' ',raw_text).strip()

print(raw_text)

messi is the first goat ronaldo is the second goat mancity will win the champoins leauge i will buy a private jet

In [155]:
#splitting using other criterias
white_space_splitting_with_special_xters = re.split(r'--r|[@^!,.#*?&]|\s', raw_text)
print(white_space_splitting_with_special_xters)

['messi', 'is', 'the', 'first', 'goat', 'ronaldo', 'is', 'the', 'second', 'goat', 'mancity', 'will', 'win', 'the', 'champoins', 'leauge', 'i', 'will', 'buy', 'a', 'private', 'jet']

In [156]:
## removing whitespaces
stripe_text = [word.strip() for word in white_space_splitting_with_special_xters if word.strip()]
len(stripe_text)

22

In [157]:
print(stripe_text)

['messi', 'is', 'the', 'first', 'goat', 'ronaldo', 'is', 'the', 'second', 'goat', 'mancity', 'will', 'win', 'the', 'champoins', 'leauge', 'i', 'will', 'buy', 'a', 'private', 'jet']

In [162]:
sorted_strip_text = sorted(set(stripe_text))
print(sorted_strip_text)

['a', 'buy', 'champoins', 'first', 'goat', 'i', 'is', 'jet', 'leauge', 'mancity', 'messi', 'private', 'ronaldo', 'second', 'the', 'will', 'win']

In [163]:
len(sorted_strip_text)

17

In [165]:
### ENUMERTE
for idx,token in enumerate(sorted_strip_text):
    print(f"({idx}, {token})")

(0, a)
(1, buy)
(2, champoins)
(3, first)
(4, goat)
(5, i)
(6, is)
(7, jet)
(8, leauge)
(9, mancity)
(10, messi)
(11, private)
(12, ronaldo)
(13, second)
(14, the)
(15, will)
(16, win)

In [168]:
vocab = {}
for idx,token in enumerate(sorted_strip_text):
    vocab[token] = idx
(vocab)

{'a': 0,
 'buy': 1,
 'champoins': 2,
 'first': 3,
 'goat': 4,
 'i': 5,
 'is': 6,
 'jet': 7,
 'leauge': 8,
 'mancity': 9,
 'messi': 10,
 'private': 11,
 'ronaldo': 12,
 'second': 13,
 'the': 14,
 'will': 15,
 'win': 16}

In [174]:
id_to_str = {}
for idx,token in enumerate(vocab):
    id_to_str[idx] = token
id_to_str

{0: 'a',
 1: 'buy',
 2: 'champoins',
 3: 'first',
 4: 'goat',
 5: 'i',
 6: 'is',
 7: 'jet',
 8: 'leauge',
 9: 'mancity',
 10: 'messi',
 11: 'private',
 12: 'ronaldo',
 13: 'second',
 14: 'the',
 15: 'will',
 16: 'win'}

In [176]:
token_ids = [vocab[word] for word in stripe_text]
print(token_ids)

[10, 6, 14, 3, 4, 12, 6, 14, 13, 4, 9, 15, 16, 14, 2, 8, 5, 15, 1, 0, 11, 7]

In [178]:
tokens_recoverd = [id_to_str[idx] for idx in token_ids]
" ".join(tokens_recoverd)

'messi is the first goat ronaldo is the second goat mancity will win the champoins leauge i will buy a private jet'